# Generated by Django 2.1b1 on 2018-07-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationconf',
            name='report',
            field=models.CharField(default='micro', max_length=50),
        ),
    ]
