# Generated by Django 2.1b1 on 2018-09-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_correlationconf_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyBNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveIntegerField()),
            ],
        ),
    ]
