# Generated by Django 2.1b1 on 2018-11-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_link',
            field=models.TextField(default='#'),
        ),
    ]
