# Generated by Django 2.0.5 on 2018-06-03 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='profile',
        ),
        migrations.AddField(
            model_name='notification',
            name='profile_from',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='profile_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='core.Profile'),
        ),
    ]
