# Generated by Django 2.0.5 on 2018-06-03 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180603_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='profile_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='core.Profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='profile_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='core.Profile'),
        ),
    ]
