# Generated by Django 2.1b1 on 2018-06-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('root_cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='causalmodel.RootCause')),
                ('root_causes_content', models.ManyToManyField(related_name='block_root_causes', to='causalmodel.RootCause')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causalmodel.Block')),
            ],
        ),
    ]
