# Generated by Django 2.1b1 on 2018-06-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0002_block_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Dad', to='causalmodel.Block'),
            preserve_default=False,
        ),
    ]
