# Generated by Django 2.1b1 on 2018-06-30 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0005_auto_20180630_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
