# Generated by Django 2.1b1 on 2018-07-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0008_auto_20180702_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='causal_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='causalmodel.CausalModel'),
        ),
    ]
