# Generated by Django 2.1b1 on 2018-07-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0009_auto_20180702_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='causalmodel',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
