# Generated by Django 2.1b1 on 2018-07-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0010_causalmodel_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causalmodel',
            name='comments',
            field=models.TextField(),
        ),
    ]
