# Generated by Django 2.1b1 on 2018-07-19 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0012_causalmodel_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causalmodel',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
