# Generated by Django 2.1b1 on 2018-07-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('causalmodel', '0014_rootcause_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausalModelComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='causalmodel',
            name='comments',
        ),
        migrations.AddField(
            model_name='causalmodelcomments',
            name='causal_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causalmodel.CausalModel'),
        ),
        migrations.AddField(
            model_name='causalmodelcomments',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
