# Generated by Django 2.1b1 on 2018-08-01 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('datapreprocessing', '0009_metric_json_data'),
        ('causalmodel', '0016_auto_20180722_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapreprocessing.Metric')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
    ]
