# Generated by Django 2.1b1 on 2018-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0017_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
