# Generated by Django 2.1b1 on 2018-08-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0018_memo_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causal_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causalmodel.CausalModel')),
            ],
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causalmodel.Box')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Father', to='causalmodel.Box')),
            ],
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='root_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causalmodel.RootCause'),
        ),
    ]
