# Generated by Django 2.1b1 on 2018-08-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0019_auto_20180802_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causalmodel.Box'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dad', to='causalmodel.Box'),
        ),
    ]
