# Generated by Django 2.1b1 on 2018-08-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0020_auto_20180802_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='barangays_addressed_to',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='suggested_interventions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
