# Generated by Django 2.0.5 on 2018-08-02 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0020_auto_20180802_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='barangays_addressed_to',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='suggested_interventions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
