# Generated by Django 2.1b1 on 2018-08-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0021_auto_20180803_0654'),
        ('causalmodel', '0021_auto_20180803_0854'),
    ]

    operations = [
    ]
