# Generated by Django 2.1b1 on 2018-10-05 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0022_merge_20180803_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='barangays_addressed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Barangay'),
        ),
    ]
