# Generated by Django 2.1b1 on 2018-10-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0027_auto_20180731_0428'),
        ('causalmodel', '0023_auto_20181005_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='barangays_addressed_to',
        ),
        migrations.AddField(
            model_name='memo',
            name='barangays_addressed_to',
            field=models.ManyToManyField(to='datainput.Barangay'),
        ),
    ]
