# Generated by Django 2.1b1 on 2018-10-30 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapreprocessing', '0010_metric_suggested_interventions'),
        ('causalmodel', '0024_auto_20181005_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('reason', models.TextField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapreprocessing.Metric')),
            ],
        ),
    ]
