# Generated by Django 2.1b1 on 2018-11-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0025_suggestedintervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedintervention',
            name='is_priority',
            field=models.BooleanField(default=True),
        ),
    ]
