# Generated by Django 2.1b1 on 2018-11-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalmodel', '0028_auto_20181107_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapreprocessing.Metric'),
        ),
        migrations.AlterField(
            model_name='suggestedintervention',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapreprocessing.Metric'),
        ),
    ]
