# Generated by Django 2.0.5 on 2018-06-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapreprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamap',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
