# Generated by Django 2.0.5 on 2018-06-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapreprocessing', '0003_auto_20180606_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapreprocessing.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='datamap',
            name='root_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapreprocessing.RootCause'),
        ),
    ]
