# Generated by Django 2.0.5 on 2018-06-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapreprocessing', '0005_metric_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamap',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='datamap',
            name='root_cause',
        ),
        migrations.DeleteModel(
            name='DataMap',
        ),
        migrations.DeleteModel(
            name='RootCause',
        ),
    ]
