# Generated by Django 2.1b1 on 2018-07-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapreprocessing', '0008_metric_threshold_bad'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='json_data',
            field=models.TextField(default=''),
        ),
    ]
