# Generated by Django 2.0.5 on 2018-06-05 02:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=20)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Barangay')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyProfileLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_no', models.CharField(max_length=20, unique=True)),
                ('no_members', models.DecimalField(decimal_places=0, max_digits=5)),
                ('count_05', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children 0 - 5 months old')),
                ('count_623', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children 6 - 23 months old')),
                ('count_2459', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children 24 - 59 months old')),
                ('count_60', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children over 60 months old')),
                ('household_head_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('educational_attainment', models.CharField(choices=[('Elementary Undergraduate', 'Elementary Undergraduate'), ('Elementary Graduate', 'Elementary Graduate'), ('Highschool Undergraduate', 'Highschool Undergraduate'), ('Highschool Graduate', 'Highschool Graduate'), ('College Undergraduate', 'College Undergraduate'), ('College Graduate', 'College Graduate'), ('Vocational', 'Vocational'), ('Others', 'Others')], max_length=50)),
                ('is_mother_pregnant', models.BooleanField()),
                ('is_family_planning', models.BooleanField()),
                ('is_ebf', models.BooleanField()),
                ('is_mixed_milk_feeding', models.BooleanField()),
                ('is_bottle_feeding', models.BooleanField()),
                ('toilet_type', models.CharField(choices=[('Water Sealed', 'Water Sealed'), ('Open Pit', 'Open Pit'), ('Others', 'Others'), ('None', 'None')], max_length=50)),
                ('water_sources', models.CharField(choices=[('Pipe', 'Pipe'), ('Well', 'Well'), ('Spring', 'Spring')], max_length=50)),
                ('food_production_activity', models.CharField(choices=[('Vegetable Garden', 'Vegetable Garden'), ('Poultry/Livestock', 'Poultry/Livestock'), ('Fishpond', 'Fishpond')], max_length=50)),
                ('is_using_iodized_salt', models.BooleanField()),
                ('is_using_ifr', models.BooleanField()),
                ('family_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.FamilyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCareWasteManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('with_syringe', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Health Centers With Syringe Collection')),
                ('with_safe_water', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Households With Access to Improved or Safe Water')),
                ('with_sanitary_toilet', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Households With Sanitary Toilet')),
                ('with_satisfactoral_disposal', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Households With Satisfactoral Disposal of Solid Waste')),
                ('with_complete_facilities', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Household With Complete Basic Sanitation Facilities')),
            ],
        ),
        migrations.CreateModel(
            name='HeightForAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InformalSettlers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('families_count', models.DecimalField(decimal_places=0, max_digits=5)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReweighing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=40)),
                ('height_for_age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.HeightForAge')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'nutritional statuses',
            },
        ),
        migrations.CreateModel(
            name='OperationTimbang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=50)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datainput.Barangay')),
            ],
        ),
        migrations.CreateModel(
            name='OPTValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.DecimalField(decimal_places=0, max_digits=7)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datainput.AgeGroup')),
                ('nutritional_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datainput.NutritionalStatus')),
                ('opt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.OperationTimbang')),
            ],
            options={
                'verbose_name_plural': 'OPT Values',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Barangay')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnemploymentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='WeightForAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WeightForHeightLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='monthlyreweighing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Patient'),
        ),
        migrations.AddField(
            model_name='monthlyreweighing',
            name='weight_for_age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.WeightForAge'),
        ),
        migrations.AddField(
            model_name='monthlyreweighing',
            name='weight_for_height_length',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.WeightForHeightLength'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Sex'),
        ),
    ]
