# Generated by Django 2.0.5 on 2018-05-27 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Barangay')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyProfileValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_no', models.CharField(max_length=20)),
                ('no_members', models.DecimalField(decimal_places=0, max_digits=5)),
                ('count_05', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children 0 - 5 months old')),
                ('count_623', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children 6 - 23 months old')),
                ('count_2459', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children 24 - 59 months old')),
                ('count_60', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children over 60 months old')),
                ('household_head_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('educational_attainment', models.CharField(max_length=50)),
                ('is_mother_pregnant', models.BooleanField(default=False)),
                ('is_family_planning', models.BooleanField(default=False)),
                ('is_ebf', models.BooleanField(default=False)),
                ('is_mixed_milk_feeding', models.BooleanField(default=False)),
                ('is_bottle_feeding', models.BooleanField(default=False)),
                ('toilet_type', models.CharField(choices=[('WS', 'WS'), ('OP', 'OP'), ('O', 'O'), ('N', 'N')], max_length=10)),
                ('water_sources', models.CharField(choices=[('P', 'P'), ('W', 'W'), ('S', 'S')], max_length=10)),
                ('food_production_activity', models.CharField(choices=[('VG', 'VG'), ('PL', 'PL'), ('FP', 'FP')], max_length=10)),
                ('is_using_iodized_salt', models.BooleanField(default=False)),
                ('is_using_ifr', models.BooleanField(default=False)),
                ('family_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.FamilyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'nutritional statuses',
            },
        ),
        migrations.CreateModel(
            name='OperationTimbang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=50)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datainput.Barangay')),
            ],
        ),
        migrations.CreateModel(
            name='OPTValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.DecimalField(decimal_places=0, max_digits=7)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datainput.AgeGroup')),
                ('nutritional_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datainput.NutritionalStatus')),
                ('opt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.OperationTimbang')),
            ],
            options={
                'verbose_name_plural': 'OPT Values',
            },
        ),
    ]
