# Generated by Django 2.0.5 on 2018-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0002_operationtimbang_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtimbang',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
