# Generated by Django 2.0.5 on 2018-06-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('datainput', '0003_auto_20180605_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='uploaded_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Profile'),
        ),
        migrations.AddField(
            model_name='monthlyreweighing',
            name='uploaded_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Profile'),
        ),
    ]
