# Generated by Django 2.0.5 on 2018-05-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0003_auto_20180526_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_no', models.CharField(max_length=20)),
                ('no_members', models.DecimalField(decimal_places=0, max_digits=5)),
                ('count_05', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children 0 - 5 months old')),
                ('count_623', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children 6 - 23 months old')),
                ('count_2459', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children 24 - 59 months old')),
                ('count_60', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Children over 60 months old')),
                ('household_head_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('educational_attainment', models.CharField(max_length=50)),
                ('is_mother_pregnant', models.BooleanField()),
                ('is_family_planning', models.BooleanField()),
                ('is_ebf', models.BooleanField()),
                ('is_mixed_milk_feeding', models.BooleanField()),
                ('is_bottle_feeding', models.BooleanField()),
                ('toilet_type', models.CharField(choices=[('WS', 'WS'), ('OP', 'OP'), ('O', 'O'), ('N', 'N')], max_length=10)),
                ('water_sources', models.CharField(choices=[('P', 'P'), ('W', 'W'), ('S', 'S')], max_length=10)),
                ('food_production_activity', models.CharField(choices=[('VG', 'VG'), ('PL', 'PL'), ('FP', 'FP')], max_length=10)),
                ('is_using_iodized_salt', models.BooleanField()),
                ('is_using_ifr', models.BooleanField()),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Barangay')),
            ],
        ),
    ]
