# Generated by Django 2.0.5 on 2018-06-05 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0004_auto_20180605_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Profile'),
        ),
        migrations.AlterField(
            model_name='monthlyreweighing',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Profile'),
        ),
    ]
