# Generated by Django 2.0.5 on 2018-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0005_auto_20180605_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informalsettlers',
            name='families_count',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Families'),
        ),
    ]
