# Generated by Django 2.0.5 on 2018-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0006_auto_20180527_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofile',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
