# Generated by Django 2.0.5 on 2018-06-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0007_auto_20180606_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='datainput.Sex'),
        ),
    ]
