# Generated by Django 2.0.5 on 2018-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0008_auto_20180527_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofileline',
            name='food_production_activity',
            field=models.CharField(choices=[('Vegetable Garden', 'Vegetable Garden'), ('Poultry/Livestock', 'Poultry/Livestock'), ('Fishpond', 'Fishpond')], max_length=50),
        ),
        migrations.AlterField(
            model_name='familyprofileline',
            name='toilet_type',
            field=models.CharField(choices=[('Water Sealed', 'Water Sealed'), ('Open Pit', 'Open Pit'), ('Others', 'Others'), ('None', 'None')], max_length=50),
        ),
        migrations.AlterField(
            model_name='familyprofileline',
            name='water_sources',
            field=models.CharField(choices=[('Pipe', 'Pipe'), ('Well', 'Well'), ('Spring', 'Spring')], max_length=50),
        ),
    ]
