# Generated by Django 2.0.5 on 2018-06-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0008_patient_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datainput.Sex'),
        ),
    ]
