# Generated by Django 2.0.5 on 2018-05-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0009_auto_20180527_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeightForAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeightForAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeightForHeightLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='optvalues',
            name='nutritional_status',
        ),
        migrations.AlterField(
            model_name='optvalues',
            name='age_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.AgeGroup'),
        ),
        migrations.DeleteModel(
            name='NutritionalStatus',
        ),
        migrations.AddField(
            model_name='optvalues',
            name='height_for_age',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='datainput.HeightForAge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optvalues',
            name='weight_for_age',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='datainput.WeightForAge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optvalues',
            name='weight_for_height_length',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='datainput.WeightForHeightLength'),
            preserve_default=False,
        ),
    ]
