# Generated by Django 2.0.5 on 2018-05-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0010_auto_20180530_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReweighing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_for_age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.HeightForAge')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Patient')),
                ('weight_for_age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.WeightForAge')),
                ('weight_for_height_length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.WeightForHeightLength')),
            ],
        ),
    ]
