# Generated by Django 2.0.5 on 2018-05-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0011_auto_20180530_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='sex',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='datainput.Sex'),
        ),
    ]
