# Generated by Django 2.0.5 on 2018-05-31 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0012_auto_20180531_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='operationtimbang',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.DataStatus'),
        ),
        migrations.AddField(
            model_name='monthlyreweighing',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='datainput.DataStatus'),
            preserve_default=False,
        ),
    ]
