# Generated by Django 2.0.5 on 2018-05-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0013_auto_20180531_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreweighing',
            name='status',
        ),
        migrations.AlterField(
            model_name='operationtimbang',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='DataStatus',
        ),
    ]
