# Generated by Django 2.0.5 on 2018-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0013_auto_20180530_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='optvalues',
            name='height_for_age',
        ),
        migrations.RemoveField(
            model_name='optvalues',
            name='weight_for_age',
        ),
        migrations.RemoveField(
            model_name='optvalues',
            name='weight_for_height_length',
        ),
    ]
