# Generated by Django 2.0.5 on 2018-05-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0014_auto_20180530_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='optvalues',
            name='nutritional_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='datainput.NutritionalStatus'),
        ),
    ]
