# Generated by Django 2.0.5 on 2018-05-31 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0014_auto_20180531_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreweighing',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
