# Generated by Django 2.0.5 on 2018-05-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0015_optvalues_nutritional_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optvalues',
            name='nutritional_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.NutritionalStatus'),
        ),
    ]
