# Generated by Django 2.0.5 on 2018-05-31 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0015_monthlyreweighing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreweighing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
