# Generated by Django 2.0.5 on 2018-06-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0015_auto_20180619_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofileline',
            name='count_05',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Number of Children 0 - 5 months old'),
        ),
        migrations.AlterField(
            model_name='familyprofileline',
            name='count_2459',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Number of Children 24 - 59 months old'),
        ),
        migrations.AlterField(
            model_name='familyprofileline',
            name='count_60',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Number of Children over 60 months old'),
        ),
        migrations.AlterField(
            model_name='familyprofileline',
            name='count_623',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Number of Children 6 - 23 months old'),
        ),
    ]
