# Generated by Django 2.1b1 on 2018-07-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0016_auto_20180621_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyprofile',
            name='status',
        ),
    ]
