# Generated by Django 2.0.5 on 2018-05-30 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0016_auto_20180530_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReweighing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('height_for_age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.HeightForAge')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='monthlyreweighing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Patient'),
        ),
        migrations.AddField(
            model_name='monthlyreweighing',
            name='weight_for_age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.WeightForAge'),
        ),
        migrations.AddField(
            model_name='monthlyreweighing',
            name='weight_for_height_length',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.WeightForHeightLength'),
        ),
    ]
