# Generated by Django 2.0.5 on 2018-05-31 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0016_auto_20180531_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreweighing',
            name='date',
        ),
    ]
