# Generated by Django 2.0.5 on 2018-05-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0017_remove_monthlyreweighing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreweighing',
            name='date',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
    ]
