# Generated by Django 2.1b1 on 2018-07-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0018_auto_20180704_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcare',
            name='received_MNP',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Infants who received MNP'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='received_iron',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Infants who received iron'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='received_vitamin_A',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Infants who received vitamin A'),
        ),
    ]
