# Generated by Django 2.0.5 on 2018-05-31 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0018_monthlyreweighing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreweighing',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
