# Generated by Django 2.1b1 on 2018-07-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0019_auto_20180706_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcare',
            name='anemic_children',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Anemic children'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='anemic_children_with_iron',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Anemic children receiving full dose iron'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='diarrhea_cases',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Diarrhea cases'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='given_complimentary_food',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Given complimentary food'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='given_deworming',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Children given deworming'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='pneumonia_cases',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pneumonia Cases'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='sick_children',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sick children'),
        ),
    ]
