# Generated by Django 2.0.5 on 2018-05-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0021_monthlyreweighing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreweighing',
            name='status',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
