# Generated by Django 2.1b1 on 2018-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0021_auto_20180706_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofileline',
            name='is_bottle_feeding',
            field=models.BooleanField(verbose_name='Is Practicing Bottled Feeding'),
        ),
        migrations.AlterField(
            model_name='familyprofileline',
            name='is_ebf',
            field=models.BooleanField(verbose_name='Is Practicing Exclusive Breastfeeding'),
        ),
        migrations.AlterField(
            model_name='familyprofileline',
            name='is_family_planning',
            field=models.BooleanField(verbose_name='Is Practicing Family Planning'),
        ),
        migrations.AlterField(
            model_name='familyprofileline',
            name='is_mixed_milk_feeding',
            field=models.BooleanField(verbose_name='Is Practicing Mixed Milk Feeding'),
        ),
        migrations.AlterField(
            model_name='familyprofileline',
            name='is_using_ifr',
            field=models.BooleanField(verbose_name='Is Using Iron Fortification'),
        ),
        migrations.AlterField(
            model_name='familyprofileline',
            name='is_using_iodized_salt',
            field=models.BooleanField(verbose_name='Is Using Iodized Salt'),
        ),
    ]
