# Generated by Django 2.0.5 on 2018-06-01 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0022_monthlyreweighing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCareWasteManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('with_syringe', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Health Centers With Syringe Collection')),
                ('with_safe_water', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Households With Access to Improved or Safe Water')),
                ('with_sanitary_toilet', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Households With Sanitary Toilet')),
                ('with_satisfactoral_disposal', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Households With Satisfactoral Disposal of Solid Waste')),
                ('with_complete_facilities', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Household With Complete Basic Sanitation Facilities')),
            ],
        ),
        migrations.CreateModel(
            name='InformalSettlers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('families_count', models.DecimalField(decimal_places=0, max_digits=5)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UnemploymentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
