# Generated by Django 2.1b1 on 2018-07-10 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0022_auto_20180706_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
