# Generated by Django 2.1b1 on 2018-07-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0023_patient_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtimbang',
            name='barangay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Barangay'),
        ),
    ]
