# Generated by Django 2.1b1 on 2018-07-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0024_auto_20180710_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='given_bcg',
            field=models.IntegerField(verbose_name='Given BCG'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='given_hepa',
            field=models.IntegerField(verbose_name='Given HEPA'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='given_mcv',
            field=models.IntegerField(verbose_name='Given MCV'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='given_opv',
            field=models.IntegerField(verbose_name='Given OPV'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='given_pcv',
            field=models.IntegerField(verbose_name='Given PCV'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='given_penta',
            field=models.IntegerField(verbose_name='Given PENTA'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='given_rota',
            field=models.IntegerField(verbose_name='Given ROTA'),
        ),
        migrations.AlterField(
            model_name='malaria',
            name='deaths',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Malaria Deaths'),
        ),
        migrations.AlterField(
            model_name='malaria',
            name='immunization_given',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Malaria Immunization Given'),
        ),
        migrations.AlterField(
            model_name='malaria',
            name='malaria_cases',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Malaria Cases'),
        ),
        migrations.AlterField(
            model_name='tuberculosis',
            name='identified',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tuberculosis Identified'),
        ),
    ]
