# Generated by Django 2.1b1 on 2018-07-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0025_auto_20180712_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofileline',
            name='no_members',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Total Members'),
        ),
    ]
